"""Project configuration: models, thresholds, and paths."""

YOLO_POSE_MODEL = "yolov8n-pose.pt"
YOLO_DEVICE = "cpu"
DETECTION_CONFIDENCE_THRESHOLD = 0.7

VIDEO_SAMPLE_EVERY_N_FRAMES = 5
ANNOTATION_DISPLAY_FRAMES = 45

HEURISTIC_HANDS_NEAR_FACE_MAX_DIST_PX = 120
HEURISTIC_HANDS_ON_HIPS_MAX_DIST_PX = 100
HEURISTIC_HAND_ON_CHEST_MAX_DIST_PX = 120
HEURISTIC_HAND_TO_NECK_MAX_DIST_PX = 100
HEURISTIC_LEGS_CLOSED_MAX_DIST_PX = 80
HEURISTIC_HANDS_CLASPED_MAX_DIST_PX = 60
HEURISTIC_BODY_TURNED_SHOULDER_DIFF_PX = 25

WHISPER_MODEL_SIZE = "tiny"
WHISPER_DEVICE = "cpu"
WHISPER_COMPUTE_TYPE = "int8"
WHISPER_LANGUAGE = "en"

OUTPUT_DIR = "output"

ANNOTATION_BOX_COLOR = (0, 255, 0)
ANNOTATION_BOX_THICKNESS = 2
ANNOTATION_FONT = 0
ANNOTATION_FONT_SCALE = 0.6
ANNOTATION_TEXT_COLOR = (255, 255, 255)
ANNOTATION_TEXT_THICKNESS = 2
ANNOTATION_BBOX_PADDING_PX = 20
